import React, { useState } from 'react';
import { DayBookEntry, CustomerLedgerEntry, ProductItem, BankAccount } from '../types';
import { X, BookOpen, Layers, Package, Wallet, CheckCircle } from 'lucide-react';
import { formatToDDMMYYYY } from '../../../utils/dateUtils';

interface AccountingAuditDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  dayBook: DayBookEntry[];
  customerLedgers: CustomerLedgerEntry[];
  products: ProductItem[];
  banks: BankAccount[];
  cashBalance: number;
}

export const AccountingAuditDrawer: React.FC<AccountingAuditDrawerProps> = ({
  isOpen,
  onClose,
  dayBook,
  customerLedgers,
  products,
  banks,
  cashBalance,
}) => {
  const [activeTab, setActiveTab] = useState<'daybook' | 'ledger' | 'stock' | 'accounts'>('daybook');

  if (!isOpen) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      className="fixed inset-0 z-50 flex items-center justify-end bg-slate-900/50 backdrop-blur-2xs animate-in fade-in"
    >
      <div className="bg-white h-full w-full max-w-2xl shadow-2xl border-l border-slate-300 flex flex-col overflow-hidden animate-in slide-in-from-right duration-200">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-blue-100 text-blue-700 rounded-lg">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">
                Accounting Integrations & Live Records
              </h2>
              <p className="text-xs text-slate-500">
                Real-time Day Book entries, customer ledgers, and store stock adjustments
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-200 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Controls */}
        <div className="flex border-b border-slate-200 px-6 bg-white gap-2">
          <button
            type="button"
            onClick={() => setActiveTab('daybook')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'daybook'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-900'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Day Book Journal ({dayBook.length})</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('ledger')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'ledger'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-900'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5" />
            <span>Customer Ledgers ({customerLedgers.length})</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('stock')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'stock'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-900'
            }`}
          >
            <Package className="w-3.5 h-3.5" />
            <span>Store Stock</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('accounts')}
            className={`py-2.5 px-3 text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'accounts'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-900'
            }`}
          >
            <Wallet className="w-3.5 h-3.5" />
            <span>Cash & Banks</span>
          </button>
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-50 text-xs">
          {/* 1. Day Book */}
          {activeTab === 'daybook' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-slate-500 text-[11px]">
                <span>All vouchers auto-generated by the Sale Invoice Module</span>
                <span className="font-semibold text-emerald-700">Balanced Double-Entry</span>
              </div>
              <div className="border border-slate-200 rounded-lg overflow-hidden bg-white shadow-2xs">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                      <th className="py-2 px-2.5">Date</th>
                      <th className="py-2 px-2">Voucher</th>
                      <th className="py-2 px-2">Invoice</th>
                      <th className="py-2 px-3">Account Title</th>
                      <th className="py-2 px-2.5 text-right">Debit (PKR)</th>
                      <th className="py-2 px-2.5 text-right">Credit (PKR)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-mono text-[11px]">
                    {dayBook.slice(-15).map((entry) => (
                      <tr key={entry.id} className="hover:bg-slate-50">
                        <td className="py-1.5 px-2.5 text-slate-500">{formatToDDMMYYYY(entry.date)}</td>
                        <td className="py-1.5 px-2 font-semibold text-blue-700">{entry.voucherNo}</td>
                        <td className="py-1.5 px-2 text-slate-600">{entry.invoiceNo}</td>
                        <td className="py-1.5 px-3 font-sans font-medium text-slate-800">
                          {entry.accountName}
                        </td>
                        <td className="py-1.5 px-2.5 text-right text-emerald-700 font-semibold">
                          {entry.debit > 0 ? entry.debit.toLocaleString() : '-'}
                        </td>
                        <td className="py-1.5 px-2.5 text-right text-blue-800 font-semibold">
                          {entry.credit > 0 ? entry.credit.toLocaleString() : '-'}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 2. Customer Ledgers */}
          {activeTab === 'ledger' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-slate-500 text-[11px]">
                <span>Customer postings for Credit Sales</span>
              </div>
              <div className="border border-slate-200 rounded-lg overflow-hidden bg-white shadow-2xs">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                      <th className="py-2 px-2.5">Date</th>
                      <th className="py-2 px-2">Invoice</th>
                      <th className="py-2 px-3">Description</th>
                      <th className="py-2 px-2 text-right">Debit</th>
                      <th className="py-2 px-2 text-right">Credit</th>
                      <th className="py-2 px-2.5 text-right">Balance</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-mono text-[11px]">
                    {customerLedgers.slice(-10).map((cl) => (
                      <tr key={cl.id} className="hover:bg-slate-50">
                        <td className="py-2 px-2.5 text-slate-500">{formatToDDMMYYYY(cl.date)}</td>
                        <td className="py-2 px-2 text-blue-700 font-bold">{cl.invoiceNo}</td>
                        <td className="py-2 px-3 font-sans text-slate-700">{cl.description}</td>
                        <td className="py-2 px-2 text-right text-rose-700">{cl.debit.toLocaleString()}</td>
                        <td className="py-2 px-2 text-right text-emerald-700">
                          {cl.credit > 0 ? cl.credit.toLocaleString() : '-'}
                        </td>
                        <td className="py-2 px-2.5 text-right font-bold text-slate-900">
                          {cl.balance.toLocaleString()} PKR
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 3. Stock per Store */}
          {activeTab === 'stock' && (
            <div className="space-y-3">
              <div className="text-slate-500 text-[11px]">
                Current inventory levels across multiple store locations (updated instantly upon sale)
              </div>
              <div className="border border-slate-200 rounded-lg overflow-hidden bg-white shadow-2xs">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                      <th className="py-2 px-3">Product Name</th>
                      <th className="py-2 px-2 text-center">Unit</th>
                      <th className="py-2 px-2.5 text-right">Main Store</th>
                      <th className="py-2 px-2.5 text-right">Warehouse A</th>
                      <th className="py-2 px-2.5 text-right">Retail Outlet</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-mono text-[11px]">
                    {products.map((p) => (
                      <tr key={p.id} className="hover:bg-slate-50">
                        <td className="py-2 px-3 font-sans font-semibold text-slate-800">
                          {p.name}
                        </td>
                        <td className="py-2 px-2 text-center text-slate-500">{p.unit}</td>
                        <td className="py-2 px-2.5 text-right text-slate-900 font-bold">
                          {p.stockByStore['store-main'] ?? 0}
                        </td>
                        <td className="py-2 px-2.5 text-right text-slate-700">
                          {p.stockByStore['store-wh-a'] ?? 0}
                        </td>
                        <td className="py-2 px-2.5 text-right text-slate-700">
                          {p.stockByStore['store-outlet'] ?? 0}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 4. Cash & Bank Balances */}
          {activeTab === 'accounts' && (
            <div className="space-y-4">
              {/* Cash in Hand */}
              <div className="p-4 bg-white rounded-lg border border-slate-200 shadow-2xs space-y-1">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Cash Account (1001)
                </span>
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-slate-800">Cash in Hand / Drawer</h3>
                  <span className="text-lg font-bold font-mono text-emerald-700">
                    {cashBalance.toLocaleString()} PKR
                  </span>
                </div>
              </div>

              {/* Bank Accounts */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Bank Accounts (1002)
                </span>
                <div className="grid grid-cols-1 gap-2.5">
                  {banks.map((b) => (
                    <div
                      key={b.id}
                      className="p-3 bg-white rounded-lg border border-slate-200 shadow-2xs flex items-center justify-between"
                    >
                      <div>
                        <h4 className="font-semibold text-slate-800 text-xs">{b.bankName}</h4>
                        <p className="text-[11px] text-slate-500 font-mono">A/C: {b.accountNumber} · {b.branch}</p>
                      </div>
                      <span className="font-bold font-mono text-blue-700 text-sm">
                        {b.balance.toLocaleString()} PKR
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 bg-white flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-md"
          >
            Close Inspector
          </button>
        </div>
      </div>
    </div>
  );
};
