import { StoreLocation, BankAccount, Customer, ProductItem, SaleInvoice, ServiceItem } from './types';
import { getCurrentDateDDMMYYYY, getFutureDateDDMMYYYY } from '../../utils/dateUtils';

export const INITIAL_STORES: StoreLocation[] = [
  { id: 'store-main', name: 'Main Store', code: 'MS-01', address: 'Plot 42, Blue Area, Islamabad' },
  { id: 'store-wh-a', name: 'Warehouse A', code: 'WH-A', address: 'Industrial Area Sector I-9, Islamabad' },
  { id: 'store-outlet', name: 'City Retail Outlet', code: 'RO-01', address: 'Commercial Market, Satellite Town, Rawalpindi' },
];

export const INITIAL_BANKS: BankAccount[] = [
  { id: 'bank-meezan', bankName: 'Meezan Bank Ltd', accountNumber: '0102-3928172901', branch: 'F-7 Markaz Branch', balance: 450000 },
  { id: 'bank-hbl', bankName: 'Habib Bank Limited (HBL)', accountNumber: '1100-7829102931', branch: 'Blue Area Corporate Branch', balance: 320000 },
  { id: 'bank-ubl', bankName: 'United Bank Limited (UBL)', accountNumber: '2201-9988112233', branch: 'Jinnah Avenue Branch', balance: 275000 },
  { id: 'bank-mcb', bankName: 'MCB Islamic Bank', accountNumber: '5509-2819201944', branch: 'Saddar Branch', balance: 185000 },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'serv-ac-gen',
    code: 'SRV-101',
    name: 'AC General Service & Gas Refill',
    description: 'Complete indoor/outdoor unit wash, filter clean, pressure testing & gas top-up',
    unit: 'Job',
    rate: 4500,
    category: 'HVAC Services',
  },
  {
    id: 'serv-lp-diag',
    code: 'SRV-102',
    name: 'Laptop Hardware Diagnostic & Chip-Level Repair',
    description: 'Motherboard IC checking, thermal paste replacement, and internal dust servicing',
    unit: 'Job',
    rate: 3500,
    category: 'IT Hardware',
  },
  {
    id: 'serv-scr-rep',
    code: 'SRV-103',
    name: 'Screen / Display Replacement Labor',
    description: 'Precision panel disassembly, bezel fitting, and calibration test',
    unit: 'Job',
    rate: 2500,
    category: 'IT Hardware',
  },
  {
    id: 'serv-sw-os',
    code: 'SRV-104',
    name: 'OS Installation & Driver Configuration',
    description: 'Licensed OS setup, official drivers, security patches & software suite',
    unit: 'Job',
    rate: 2000,
    category: 'Software',
  },
  {
    id: 'serv-prt-mnt',
    code: 'SRV-105',
    name: 'Printer Maintenance & Head Cleaning',
    description: 'Laser toner drum cleaning, pickup roller check & print head realignment',
    unit: 'Job',
    rate: 3000,
    category: 'Printing Equipment',
  },
  {
    id: 'serv-veh-oil',
    code: 'SRV-106',
    name: 'Vehicle Routine Oil & Filter Service',
    description: 'Synthetic oil drain & refill, oil filter replacement, and 20-point mechanical check',
    unit: 'Job',
    rate: 3500,
    category: 'Automotive',
  },
  {
    id: 'serv-net-cab',
    code: 'SRV-107',
    name: 'Network Cabling & Patch Panel Setup',
    description: 'Cat6 structured cabling per drop, RJ45 termination, and switch port testing',
    unit: 'Node',
    rate: 1500,
    category: 'Networking',
  },
  {
    id: 'serv-gen-insp',
    code: 'SRV-108',
    name: 'General Electrical & Technical Inspection',
    description: 'Site load test, wiring integrity audit, and diagnostic report generation',
    unit: 'Job',
    rate: 5000,
    category: 'Technical Inspection',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-ali-traders',
    name: 'Ali Traders',
    phone: '+92 300 1234567',
    email: 'alitrader@example.com',
    address: 'Shop No. 12, Main Market, Lahore',
    previousBalance: 15000,
    creditLimit: 200000,
    isSupplier: false,
    supplierPayableBalance: 0,
    linkedAssets: [
      { id: 'asset-1', name: 'Toyota Corolla (LEA-1234)', type: 'Vehicle', identifier: 'LEA-1234' },
      { id: 'asset-2', name: 'Dell Latitude 7490 Laptop', type: 'Laptop', identifier: 'SN-DL7490-X1' },
    ],
  },
  {
    id: 'cust-1',
    name: 'Ali Trader',
    phone: '+92 300 1234567',
    email: 'alitrader@example.com',
    address: 'Shop 14, Commercial Market, Rawalpindi',
    previousBalance: 50000,
    creditLimit: 200000,
    isSupplier: true,
    supplierPayableBalance: 45000,
    linkedAssets: [
      { id: 'asset-3', name: 'Honda Civic (ICT-9821)', type: 'Vehicle', identifier: 'ICT-9821' },
    ],
  },
  {
    id: 'cust-2',
    name: 'Ahmed Electronics',
    phone: '+92 321 9876543',
    email: 'ahmed.elec@example.com',
    address: 'Hall Road Plaza, Lahore',
    previousBalance: 125000,
    creditLimit: 300000,
    isSupplier: true,
    supplierPayableBalance: 80000,
    linkedAssets: [
      { id: 'asset-4', name: 'Haier 1.5 Ton DC Inverter AC', type: 'AC', identifier: 'HR-INV-01' },
      { id: 'asset-5', name: 'HP LaserJet Pro M404n', type: 'Equipment', identifier: 'HP-M404-98' },
    ],
  },
  {
    id: 'cust-3',
    name: 'Fresh Markets Ltd',
    phone: '+92 333 4455667',
    email: 'orders@freshmarkets.pk',
    address: 'G-9 Markaz, Islamabad',
    previousBalance: 0,
    creditLimit: 150000,
    isSupplier: false,
    supplierPayableBalance: 0,
    linkedAssets: [
      { id: 'asset-6', name: 'Suzuki Carry Van (RIP-4401)', type: 'Vehicle', identifier: 'RIP-4401' },
    ],
  },
  {
    id: 'cust-4',
    name: 'City Traders & Co',
    phone: '+92 345 7788990',
    email: 'citytraders@example.com',
    address: 'Main Bazar, Gujranwala',
    previousBalance: 35000,
    creditLimit: 100000,
    isSupplier: false,
    supplierPayableBalance: 0,
    linkedAssets: [
      { id: 'asset-7', name: 'Yamaha YBR 125 Bike (RIM-452)', type: 'Bike', identifier: 'RIM-452' },
    ],
  },
  {
    id: 'cust-5',
    name: 'Bilal General Store',
    phone: '+92 312 3344556',
    email: 'bilalgen@example.com',
    address: 'Sector F-10/2, Islamabad',
    previousBalance: 82500,
    creditLimit: 250000,
    isSupplier: true,
    supplierPayableBalance: 15000,
    linkedAssets: [
      { id: 'asset-8', name: 'Gree 2.0 Ton Floor Standing AC', type: 'AC', identifier: 'GR-FL-20' },
    ],
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-hp-15',
    code: '500300001',
    name: 'HP Laptop 15',
    description: 'HP Laptop 15 i5',
    unit: 'PCS',
    salePrice: 500,
    costPrice: 400,
    stockByStore: { 'store-main': 45, 'store-wh-a': 100, 'store-outlet': 15 },
  },
  {
    id: 'prod-mouse-wl',
    code: '500300002',
    name: 'Mouse Wireless',
    description: 'HP Laptop 15',
    unit: 'PCS',
    salePrice: 500,
    costPrice: 350,
    stockByStore: { 'store-main': 120, 'store-wh-a': 250, 'store-outlet': 30 },
  },
  {
    id: 'prod-keyboard-pcs',
    code: '500300003',
    name: 'Keyboard',
    description: 'PCS',
    unit: 'PCS',
    salePrice: 500,
    costPrice: 380,
    stockByStore: { 'store-main': 85, 'store-wh-a': 150, 'store-outlet': 25 },
  },
  {
    id: 'prod-monitor-22',
    code: '500300001',
    name: 'Monitor 22"',
    description: 'Cash Sale',
    unit: 'Unit',
    salePrice: 4500,
    costPrice: 3800,
    stockByStore: { 'store-main': 35, 'store-wh-a': 50, 'store-outlet': 10 },
  },
  {
    id: 'prod-printer-wp',
    code: '500300002',
    name: 'Printer',
    description: 'WordPress Accounting Solution',
    unit: 'Unit',
    salePrice: 4500,
    costPrice: 3600,
    stockByStore: { 'store-main': 20, 'store-wh-a': 40, 'store-outlet': 5 },
  },
  {
    id: 'prod-1',
    code: 'IT-101',
    name: 'Dell Latitude Core i7 Laptop',
    description: '16GB RAM, 512GB NVMe SSD, 14-inch FHD Display',
    unit: 'Pcs',
    salePrice: 97500,
    costPrice: 85000,
    stockByStore: { 'store-main': 24, 'store-wh-a': 40, 'store-outlet': 10 },
  },
  {
    id: 'prod-2',
    code: 'IT-102',
    name: 'Logitech Wireless Mouse',
    description: '2.4GHz Optical Mouse with USB Nano Receiver',
    unit: 'Pcs',
    salePrice: 1500,
    costPrice: 1050,
    stockByStore: { 'store-main': 148, 'store-wh-a': 200, 'store-outlet': 45 },
  },
  {
    id: 'prod-3',
    code: 'IT-103',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB Backlit Blue Switches with Anti-Ghosting',
    unit: 'Pcs',
    salePrice: 4500,
    costPrice: 3200,
    stockByStore: { 'store-main': 58, 'store-wh-a': 80, 'store-outlet': 20 },
  },
  {
    id: 'prod-4',
    code: 'IT-104',
    name: 'HP LaserJet Pro MFP Printer',
    description: 'Monochrome Print, Scan, Copy with Auto Duplex',
    unit: 'Pcs',
    salePrice: 38500,
    costPrice: 32000,
    stockByStore: { 'store-main': 16, 'store-wh-a': 30, 'store-outlet': 5 },
  },
  {
    id: 'prod-5',
    code: 'IT-105',
    name: 'Samsung 27-inch IPS Monitor',
    description: '75Hz FreeSync Ultra-Slim Bezel Full HD',
    unit: 'Pcs',
    salePrice: 42000,
    costPrice: 36000,
    stockByStore: { 'store-main': 35, 'store-wh-a': 50, 'store-outlet': 8 },
  },
  {
    id: 'prod-6',
    code: 'GR-201',
    name: 'Super Kernel Basmati Rice 25kg',
    description: 'Premium Aged Long Grain Export Quality',
    unit: 'Bag',
    salePrice: 6500,
    costPrice: 5400,
    stockByStore: { 'store-main': 120, 'store-wh-a': 500, 'store-outlet': 40 },
  },
  {
    id: 'prod-7',
    code: 'GR-202',
    name: 'Refined White Sugar 50kg',
    description: 'Pure Cane Refined Sugar Industrial Grade',
    unit: 'Bag',
    salePrice: 7200,
    costPrice: 6100,
    stockByStore: { 'store-main': 80, 'store-wh-a': 400, 'store-outlet': 30 },
  },
];

export const INITIAL_INVOICES: SaleInvoice[] = [
  {
    id: 'inv-cs-01',
    invoiceNo: 'SI-000001',
    transactionNo: 'TXN-000001',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Ali Traders',
    customerId: 'cust-1',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs1-1',
        productId: 'prod-keyboard-pcs',
        productName: 'Keyboard & Mouse Set',
        description: 'Office accessories bundle',
        unit: 'PCS',
        quantity: 10,
        rate: 5000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 50000,
        stockNumber: '500300001',
      },
    ],
    subtotal: 50000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 50000,
    previousBalance: 0,
    cashReceivedAtSale: 50000,
    cashReceivedAmount: 50000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 50000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'inv-cs-02',
    invoiceNo: 'SI-000002',
    transactionNo: 'TXN-000002',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Ahmed Khan',
    customerId: 'cust-2',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs2-1',
        productId: 'prod-mouse-wireless',
        productName: 'Mouse Wireless Optical',
        description: 'Wireless ergonomic mice',
        unit: 'PCS',
        quantity: 20,
        rate: 1500,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 30000,
        stockNumber: '500300002',
      },
    ],
    subtotal: 30000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 30000,
    previousBalance: 0,
    cashReceivedAtSale: 30000,
    cashReceivedAmount: 30000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 30000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T10:30:00.000Z',
  },
  {
    id: 'inv-cs-03',
    invoiceNo: 'SI-000003',
    transactionNo: 'TXN-000003',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-wh-a',
    storeLocationName: 'Warehouse A',
    customerName: 'Ali Traders',
    customerId: 'cust-1',
    paymentMethod: 'Cash (Bank deposit)',
    bankAccountId: 'bank-meezan',
    bankName: 'Meezan Bank Ltd',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs3-1',
        productId: 'prod-printer-wp',
        productName: 'LaserJet Multifunction Printer',
        description: 'Office network printer',
        unit: 'Unit',
        quantity: 1,
        rate: 50000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 50000,
        stockNumber: '500300003',
      },
    ],
    subtotal: 50000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 50000,
    previousBalance: 0,
    cashReceivedAtSale: 15000,
    cashReceivedAmount: 0,
    bankReceivedAmount: 15000,
    totalReceivedAmount: 15000,
    remainingBalanceAmount: 35000,
    currentInvoiceRemaining: 35000,
    finalCustomerBalance: 35000,
    status: 'PARTIAL CREDIT',
    createdAt: '2026-01-15T11:00:00.000Z',
  },
  {
    id: 'inv-cs-04',
    invoiceNo: 'SI-000004',
    transactionNo: 'TXN-000004',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Walk-in',
    customerId: undefined,
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs4-1',
        productId: 'prod-monitor-22',
        productName: 'Monitor 22" LED IPS',
        description: 'FHD office display',
        unit: 'Unit',
        quantity: 2,
        rate: 25000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 50000,
        stockNumber: '500300004',
      },
    ],
    subtotal: 50000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 50000,
    previousBalance: 0,
    cashReceivedAtSale: 50000,
    cashReceivedAmount: 50000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 50000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T11:45:00.000Z',
  },
  {
    id: 'inv-cs-05',
    invoiceNo: 'SI-000005',
    transactionNo: 'TXN-000005',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-outlet',
    storeLocationName: 'City Retail Outlet',
    customerName: 'Ahmed Khan',
    customerId: 'cust-2',
    paymentMethod: 'Cash (Bank deposit)',
    bankAccountId: 'bank-hbl',
    bankName: 'Habib Bank Limited (HBL)',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs5-1',
        productId: 'prod-laptop-hp',
        productName: 'HP ProBook 450 G8 Core i5',
        description: 'Business laptop 8GB/256GB',
        unit: 'Unit',
        quantity: 1,
        rate: 70000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 70000,
        stockNumber: '500300005',
      },
    ],
    subtotal: 70000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 70000,
    previousBalance: 0,
    cashReceivedAtSale: 70000,
    cashReceivedAmount: 0,
    bankReceivedAmount: 70000,
    totalReceivedAmount: 70000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T12:15:00.000Z',
  },
  {
    id: 'inv-cs-06',
    invoiceNo: 'SI-000006',
    transactionNo: 'TXN-000006',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Ali Traders',
    customerId: 'cust-1',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs6-1',
        productId: 'prod-ssd-1tb',
        productName: 'NVMe M.2 1TB Solid State Drive',
        description: 'High-speed storage batch',
        unit: 'PCS',
        quantity: 10,
        rate: 10000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 100000,
        stockNumber: '500300006',
      },
    ],
    subtotal: 100000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 100000,
    previousBalance: 0,
    cashReceivedAtSale: 100000,
    cashReceivedAmount: 100000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 100000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T13:00:00.000Z',
  },
  {
    id: 'inv-cs-07',
    invoiceNo: 'SI-000007',
    transactionNo: 'TXN-000007',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Ahmed Khan',
    customerId: 'cust-2',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs7-1',
        productId: 'prod-laptop-hp',
        productName: 'HP EliteBook Core i7 Quad Core',
        description: 'Corporate workstation laptops',
        unit: 'Unit',
        quantity: 2,
        rate: 125000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 250000,
        stockNumber: '500300007',
      },
    ],
    subtotal: 250000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 250000,
    previousBalance: 0,
    cashReceivedAtSale: 250000,
    cashReceivedAmount: 250000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 250000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T14:10:00.000Z',
  },
  {
    id: 'inv-cs-08',
    invoiceNo: 'SI-000008',
    transactionNo: 'TXN-000008',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-outlet',
    storeLocationName: 'City Retail Outlet',
    customerName: 'Walk-in',
    customerId: undefined,
    paymentMethod: 'Petty Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs8-1',
        productId: 'prod-monitor-22',
        productName: 'Monitor 24" Curved Gaming Display',
        description: 'High refresh rate displays',
        unit: 'Unit',
        quantity: 5,
        rate: 39000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 195000,
        stockNumber: '500300008',
      },
    ],
    subtotal: 195000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 195000,
    previousBalance: 0,
    cashReceivedAtSale: 195000,
    cashReceivedAmount: 195000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 195000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T15:20:00.000Z',
  },
  {
    id: 'inv-cs-09',
    invoiceNo: 'SI-000009',
    transactionNo: 'TXN-000009',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Walk-in',
    customerId: undefined,
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs9-1',
        productId: 'prod-printer-wp',
        productName: 'Thermal POS Barcode Receipt Printers',
        description: 'High-speed retail counter printers',
        unit: 'Unit',
        quantity: 10,
        rate: 14000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 140000,
        stockNumber: '500300009',
      },
    ],
    subtotal: 140000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 140000,
    previousBalance: 0,
    cashReceivedAtSale: 140000,
    cashReceivedAmount: 140000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 140000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T16:00:00.000Z',
  },
  {
    id: 'inv-cs-10',
    invoiceNo: 'SI-000010',
    transactionNo: 'TXN-000010',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-outlet',
    storeLocationName: 'City Retail Outlet',
    customerName: 'Walk-in',
    customerId: undefined,
    paymentMethod: 'Petty Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs10-1',
        productId: 'prod-ups-1200va',
        productName: 'Online Sine-Wave UPS 1200VA',
        description: 'Backup power units for cash counter',
        unit: 'Unit',
        quantity: 5,
        rate: 39000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 195000,
        stockNumber: '500300010',
      },
    ],
    subtotal: 195000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 195000,
    previousBalance: 0,
    cashReceivedAtSale: 195000,
    cashReceivedAmount: 195000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 195000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T16:45:00.000Z',
  },
  {
    id: 'inv-cs-12',
    invoiceNo: 'SI-000012',
    transactionNo: 'TXN-000012',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerName: 'Walk-in',
    customerId: undefined,
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs12-1',
        productId: 'prod-ram-16gb',
        productName: 'DDR4 16GB 3200MHz RAM Modules',
        description: 'Desktop high-performance memory',
        unit: 'PCS',
        quantity: 15,
        rate: 10000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 150000,
        stockNumber: '500300012',
      },
    ],
    subtotal: 150000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 150000,
    previousBalance: 0,
    cashReceivedAtSale: 150000,
    cashReceivedAmount: 150000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 150000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T17:15:00.000Z',
  },
  {
    id: 'inv-cs-13',
    invoiceNo: 'SI-000013',
    transactionNo: 'TXN-000013',
    invoiceDate: '15/01/2026',
    dueDate: '15/01/2026',
    saleType: 'Cash Sale',
    storeLocationId: 'store-wh-a',
    storeLocationName: 'Warehouse A',
    customerName: 'Ali Traders',
    customerId: 'cust-1',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cs13-1',
        productId: 'prod-server-rack',
        productName: 'Enterprise Server Rack & Network Hardware',
        description: 'Complete data center setup hardware',
        unit: 'Set',
        quantity: 1,
        rate: 870000,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 870000,
        stockNumber: '500300013',
      },
    ],
    subtotal: 870000,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 870000,
    previousBalance: 0,
    cashReceivedAtSale: 870000,
    cashReceivedAmount: 870000,
    bankReceivedAmount: 0,
    totalReceivedAmount: 870000,
    remainingBalanceAmount: 0,
    currentInvoiceRemaining: 0,
    finalCustomerBalance: 0,
    status: 'PAID IN FULL',
    createdAt: '2026-01-15T17:45:00.000Z',
  },
  {
    id: 'inv-cr-02',
    invoiceNo: 'SI-000014',
    transactionNo: 'TXN-000014',
    invoiceDate: '16/01/2026',
    dueDate: '01/02/2026',
    saleType: 'Credit Sale',
    storeLocationId: 'store-main',
    storeLocationName: 'Main Store',
    customerId: 'cust-1',
    customerName: 'Ali Traders',
    customerPhone: '+92 300 1234567',
    customerAddress: 'Shop 14, Commercial Market, Rawalpindi',
    paymentMethod: 'Cash',
    salesman: 'Ali Khan',
    items: [
      {
        id: 'item-cr2-1',
        productId: 'prod-laptop-hp',
        productName: 'Dell Latitude Core i7 Laptop',
        description: '16GB RAM, 512GB SSD',
        unit: 'Pcs',
        quantity: 1,
        rate: 97500,
        discountType: 'fixed',
        discountValue: 0,
        discountAmount: 0,
        taxPercent: 0,
        taxAmount: 0,
        total: 97500,
        stockNumber: '500300014',
      },
    ],
    subtotal: 97500,
    overallDiscount: 0,
    overallTax: 0,
    netInvoiceTotal: 97500,
    previousBalance: 50000,
    cashReceivedAtSale: 27500,
    cashReceivedAmount: 27500,
    bankReceivedAmount: 0,
    totalReceivedAmount: 27500,
    remainingBalanceAmount: 70000,
    currentInvoiceRemaining: 70000,
    finalCustomerBalance: 120000,
    status: 'PARTIAL CREDIT',
    createdAt: '2026-01-16T14:30:00.000Z',
  },
];
